services:
  # api:
  #   build: .
  #   container_name: fastapi-app
  #   ports:
  #     - "8000:8000" # FastAPI default port, access at http://localhost:8000
  #   depends_on:
  #     - redis
  #   env_file:
  #     - .env
  #   networks:
  #     - shoppy_network
  redis:
    image: redis:6.0-alpine
    container_name: redis_broker
    ports:
      - "6379:6379" # Redis default porte, access at redis://localhost:6379
    volumes:
      - redis_data:/data

  worker:
    build: .
    container_name: celery-worker
    command: celery -A worker worker --loglevel=info
    volumes:
      - .:/backend
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/backend
    env_file:
      - .env
    networks:
      - shoppy_network

volumes:
  redis_data:

networks:
  shoppy_network:
