services:
  redis:
    image: redis:6.0-alpine
    container_name: redis_broker
    ports:
      - "6379:6379" # Redis default port, access at redis://localhost:6379
    volumes:
      - redis_data:/data

volumes:
  redis_data:
